### ISSUE TITLE
A code issue in Chapter 3

### ISSUE THREAD

**Issue by aguluman** [cwoodruff/book-network-programming-csharp#7]
In here, https://csharp-networking.com/chapter03/#session-timeouts

The remove keyword raised a problem in the IDE. ```The issue is caused by the use of the Remove method on [ConcurrentDictionary], which does not exist. Instead, you should use the TryRemove method. ```

![image](https://github.com/user-attachments/assets/249e747c-db47-4656-b801-744d4f07cfc2)

**Comment by cwoodruff** [comment]
Thanks! Fixed and acknowledged.
