### ISSUE TITLE
Chapter. 3 Concurrent collections for client management, no usage of concurrent collections

### ISSUE THREAD

**Issue by semuserable** [cwoodruff/book-network-programming-csharp#9]
You provided a statement `The System.Collections.Concurrent namespace provides thread-safe collections`, but in the code you're not showing any usage of concurrent collections. `List<T>` with `lock` is just a thread-safe access pattern, but not a concurrent collection.

**Comment by cwoodruff** [comment]
Thanks. The code has been refactored, and the chapter has been updated. Appreciate the feedback
